% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Environmental exposures and geo-social determinants of health as they impact cognition},
  pdfauthor={Gabrielle Husted},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Environmental exposures and geo-social determinants of health as
they impact cognition}
\author{Gabrielle Husted}
\date{2023-12-13}

\begin{document}
\maketitle

One in three seniors die with Alzheimer's disease and/or related
dementia (ADRD), according to the Alzheimer's Association. The expected
proportion of the population with ADRD is anticipated to increase
substantially, particularly as a result of the nebulous etiology, lack
of treatment options, and the demographic shift toward an aging
population. There are many potential points of intervention to explore
in pursuit of ameliorating ADRD; socioeconomic factors, education,
access to healthcare, genetics, and lifestyle factors can all play a
role. Through a geo-social determinants of health lens, my work
investigates the role of chemical toxicants in the development and
exacerbation of ADRD.

The distribution of people, and consequently, their unequal exposure to
environmental hazards, is a function of their socio-demographics.
Neighborhood resources are shaped by the composition of neighborhoods
and communities. This is seen through decisions such as where to locate
new schools, healthy grocery stores, and companies that pollute.

We argue that one facet of neighborhood disadvantage -- toxic chemical
exposure -- plays a prominent role in the disparate development and
exacerbation of ADRD neuropathology across communities. Our work focuses
specifically on phthalates as the toxic chemical exposures of interest.

Phthalates are the chemicals used to make plastics flexible and durable.
They do not chemically bind to the material they are added to, which
leads to them being readily absorbed into the human body. They can make
their way into bodies through leaching into food or water that has been
stored in containers made with phthalates, exposure to airborne
phthalate particles when working with materials such as plastic piping
or synthetic furniture, and our skin can absorb phthalates from lotion
and cosmetics.

Prior research has demonstrated associations between exposure to
phthalates and detrimental health impacts -- including child brain
development, metabolic complications, reduced educational achievement
due to learning and attention disorders, and greater incidence of
allergies.

Phthalates make their way to the gut and impact the gut microbiome in
ways relevant to ADRD, which supports exploring to see if phthalate
concentrations are related to other ADRD outcomes. For example, exposure
to DEHP, diethylhexyl phthalate, is associated with changes in the gut
microbiome that alters the proportion of microbes in negative ways,
leading to increased production of metabolites that are known to be
correlated with neurodevelopment disorders. Dysbiosis in the gut is
caused by chronic diseases (such as inflammatory bowel disease), diet,
infection, and antibiotics, and, environmental chemicals are emerging as
key contributors to gut dysbiosis.

There is a relationship between socio-demographic factors and social
determinants of health, and both influence exposure to phthalates and
cognitive health.

The EPA has recently emphasized its focus on the cumulative effects of
``chemical and non-chemical stressors'' on health outcomes, which
motivates our work examining the relationship between density of TRI
releasing phthalate chemicals (chemical stressors) and cognitive health
outcomes, accounting for various socio-demographic characteristics --
specifically education, age, race/ethnicity, and household income
(non-chemical stressors).

\hypertarget{research-question}{%
\subsection{Research Question:}\label{research-question}}

How does cognition and Alzheimer's neuropathology vary within the U.S.
population in relation to geo-social determinants of health,
specifically locations of and pollutants released by industries in the
TRI?

\hypertarget{hypothesis}{%
\subsection{Hypothesis:}\label{hypothesis}}

Hypothesis: States with more toxic phthalate industries have higher
prevalence of the population with two or more cognitive impairments.
Age, race/ethnicity, education, and income all contribute to moderating
the relationship between \# of phthalate facilities and cognitive
health.

We anticipate that toxic industries are located in greater numbers and
closer to communities with larger proportions of marginalized
individuals, people of lower educational attainment and lower income
level, and people with inadequate resources to mitigate harm. Informed
by the literature identifying environmental risk factors for ADRD, we
expect that our analysis will reflect that ADRD is more prevalent in
communities with greater numbers of toxic manufacturing and facilities
contributing to toxic chemical releases (air, water, or land disposal).

\hypertarget{getting-started-by-loading-necessary-packages}{%
\subsection{Getting started by loading necessary
packages}\label{getting-started-by-loading-necessary-packages}}

\hypertarget{data}{%
\subsection{Data}\label{data}}

\hypertarget{panel-study-of-income-dynamics-psid}{%
\subsubsection{Panel Study of Income Dynamics
(PSID)}\label{panel-study-of-income-dynamics-psid}}

PSID has some geographic information publicly available -- region and
state of residence

The PSID is the longest running longitudinal household study in the
world. It began in 1968 and has collected data annually from 1968-1997,
and biennially 1997 onward. It includes 18,000 individuals living in
5,000 families in the US and it is a nationally representative sample.
Descendants of these families are included in the data collection, which
naturally grows the sample. Some health variables: disability, chronic
health conditions, health status, BMI, health behaviors, health care
expenditures, mental health, dementia screener, child health, and
mortality.

Only has state level data is publicly available, so that is what is used
for this project, however, I plan to apply for and use restricted
block-level data for my dissertation.

The average prevalence of someone responding that they have two or more
cognitive measures of impairment is a median of 150 people and a mean of
181 people, and the variation does not appear to be randomly or equally
distributed.

** I plan to analyze years 2017-2022 for my dissertation, but merging
the waves of data across the years is way more difficult than a few
weeks of work would allow, but it will be really worthwhile for my
dissertation. **

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# PSID CLEANING}

\CommentTok{\# data center automatically makes the merge if you include both family level and individual level variables in your data cart}

\NormalTok{psid }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"/Users/gabriellebenoit/Documents/GitHub/EDS\_222/EDS222\_FinalProject/J327273.xlsx"}\NormalTok{)}

\CommentTok{\# rename the variables}
\NormalTok{psid }\OtherTok{\textless{}{-}}\NormalTok{ psid }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{intnum =}\NormalTok{ ER30001, }
         \AttributeTok{persnum =}\NormalTok{ ER30002, }
         \AttributeTok{STATEFP =}\NormalTok{ ER66004, }
         \AttributeTok{age =}\NormalTok{ ER66017, }
         \AttributeTok{perloss =}\NormalTok{ ER68469, }
         \AttributeTok{lossage =}\NormalTok{ ER68471, }
         \AttributeTok{losslimit =}\NormalTok{ ER68472, }
         \AttributeTok{lossmeds =}\NormalTok{ ER68473, }
         \AttributeTok{decis =}\NormalTok{ ER68503, }
         \AttributeTok{changethink =}\NormalTok{ ER68510, }
         \AttributeTok{permlossspouse =}\NormalTok{ ER69596, }
         \AttributeTok{lossagespouse =}\NormalTok{ ER69598, }
         \AttributeTok{losslimitspouse =}\NormalTok{ ER69599, }
         \AttributeTok{lossmedsspouse =}\NormalTok{ ER69600, }
         \AttributeTok{decisspouse =}\NormalTok{ ER69630, }
         \AttributeTok{changethinkspouse =}\NormalTok{ ER69637, }
         \AttributeTok{race =}\NormalTok{ ER70882, }
         \AttributeTok{highestedu =}\NormalTok{ ER70891, }
         \AttributeTok{censusneeds =}\NormalTok{ ER71528, }
         \AttributeTok{intnum2017 =}\NormalTok{ ER34501, }
         \AttributeTok{seqnum =}\NormalTok{ ER34502, }
         \AttributeTok{reltoref =}\NormalTok{ ER34503, }
         \AttributeTok{decisnotref =}\NormalTok{ ER34582, }
         \AttributeTok{dailyprob =}\NormalTok{ ER34589, }
         \AttributeTok{twoplus =}\NormalTok{ ER34590)}

\NormalTok{psid}\SpecialCharTok{$}\NormalTok{plustwo }\OtherTok{=}\NormalTok{ (psid}\SpecialCharTok{$}\NormalTok{twoplus }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{psid}\SpecialCharTok{$}\NormalTok{plustwo }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(psid}\SpecialCharTok{$}\NormalTok{twoplus }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{\# Load \textquotesingle{}crosswalk\textquotesingle{} data for states}
\NormalTok{crosswalk }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"/Users/gabriellebenoit/Documents/GitHub/EDS\_222/EDS222\_FinalProject/crosswalk.xlsx"}\NormalTok{)}

\CommentTok{\# create a measure of how many people answering yes to 2+ in each state}
\NormalTok{psid\_collapsed }\OtherTok{\textless{}{-}}\NormalTok{ psid }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(STATEFP) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(}\AttributeTok{twoplus =} \FunctionTok{sum}\NormalTok{(twoplus), }\AttributeTok{totaln =} \FunctionTok{n}\NormalTok{())}
\FunctionTok{summary}\NormalTok{(psid\_collapsed}\SpecialCharTok{$}\NormalTok{twoplus)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00   35.25  150.50  180.90  245.75  827.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{psid\_collapsed}\SpecialCharTok{$}\NormalTok{prop }\OtherTok{\textless{}{-}}\NormalTok{ psid\_collapsed}\SpecialCharTok{$}\NormalTok{twoplus}\SpecialCharTok{/}\NormalTok{psid\_collapsed}\SpecialCharTok{$}\NormalTok{totaln}
\end{Highlighting}
\end{Shaded}

I loaded in the PSID data for year 2017. I relabeled the variables to
make more intuitive sense. I created a binary variable to determine
whether respondents answered yes to having two or more cognitive
impairments, or no. I also created an aggregate measure of how many
people in each state answer yes to having two or more cognitive
impairments. Then, I loaded in state data from the U.S. Census, so that
I'd be able to merge my three datasets ultimately by U.S.
state/territory

\hypertarget{toxic-release-inventory-tri}{%
\subsubsection{Toxic Release Inventory
(TRI)}\label{toxic-release-inventory-tri}}

There are over 770 individual chemicals, 33 chemical categories included
in the TRI. The TRI publishes new data each year in July, and updates
the database several times throughout the year. Generally it includes
chemicals that cause: cancer or other chronic health effects,
significant adverse acute human health effects, significant adverse
environmental effects

The TRI documents both toxic chemical releases (into air, water, or land
disposal) and pollution prevention activities reported by industrial and
federal facilities. Facilities that report to the TRI include:
manufacturing, metal mining , electric power generation, chemical
manufacturing, hazardous waste treatment.

When we subset to just our chemical of interest, phthalates, there are
280 phthalate facilities in the U.S., with the most in Texas, and the
least in 14 states/territories that have no phthalate facilities --
Alaska, Colorado, Delaware, Hawaii, Maine, Montana, America Samoa,
Commonwealth of the Northern Mariana Islands, District of Columbia,
Guam, South Dakota, United States Virgin Islands, Vermont, Wyoming

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# load in the TRI data}
\NormalTok{tri2017 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"/Users/gabriellebenoit/Documents/GitHub/EDS\_222/EDS222\_FinalProject/2017\_us.csv"}\NormalTok{)}

\DocumentationTok{\#\# TRI CLEANING}
\CommentTok{\# fixing the unwieldy names}
\FunctionTok{names}\NormalTok{(tri2017) }\OtherTok{=} \FunctionTok{gsub}\NormalTok{(}\StringTok{"X}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{d+}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{."}\NormalTok{, }\StringTok{""}\NormalTok{, }\FunctionTok{names}\NormalTok{(tri2017))}
\FunctionTok{names}\NormalTok{(tri2017) }\OtherTok{=} \FunctionTok{gsub}\NormalTok{(}\StringTok{"[0{-}9}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{d}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.ABCD]+}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{."}\NormalTok{, }\StringTok{""}\NormalTok{, }\FunctionTok{names}\NormalTok{(tri2017))}
\FunctionTok{names}\NormalTok{(tri2017)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] "YEAR"                       "TRIFD"                     
##   [3] "FRS.ID"                     "FACILITY.NAME"             
##   [5] "STREET.ADDRESS"             "CITY"                      
##   [7] "COUNTY"                     "ST"                        
##   [9] "ZIP"                        "BIA"                       
##  [11] "TRIBE"                      "LATITUDE"                  
##  [13] "LONGITUDE"                  "HORIZONTAL.DATUM"          
##  [15] "PARENT.CO.NAME"             "PARENT.CO.DB.NUM"          
##  [17] "STANDARD.PARENT.CO.NAME"    "FEDERAL.FACILITY"          
##  [19] "INDUSTRY.SECTOR.CODE"       "INDUSTRY.SECTOR"           
##  [21] "PRIMARY.SIC"                "SIC.2"                     
##  [23] "SIC.3"                      "SIC.4"                     
##  [25] "SIC.5"                      "SIC.6"                     
##  [27] "PRIMARY.NAICS"              "NAICS.2"                   
##  [29] "NAICS.3"                    "NAICS.4"                   
##  [31] "NAICS.5"                    "NAICS.6"                   
##  [33] "DOC_CTRL_NUM"               "CHEMICAL"                  
##  [35] "ELEMENTAL.METAL.INCLUDED"   "TRI.CHEMICAL.COMPOUND.ID"  
##  [37] "CAS."                       "SRS.ID"                    
##  [39] "CLEAN.AIR.ACT.CHEMICAL"     "CLASSIFICATION"            
##  [41] "METAL"                      "METAL.CATEGORY"            
##  [43] "CARCINOGEN"                 "PBT"                       
##  [45] "PFAS"                       "FORM.TYPE"                 
##  [47] "UNIT.OF.MEASURE"            "FUGITIVE.AIR"              
##  [49] "STACK.AIR"                  "WATER"                     
##  [51] "UNDERGROUND"                "UNDERGROUND.CL.I"          
##  [53] "UNDERGROUND.C.II.V"         "LANDFILLS"                 
##  [55] "RCRA.C.LANDFILL"            "OTHER.LANDFILLS"           
##  [57] "LAND.TREATMENT"             "SURFACE.IMPNDMNT"          
##  [59] "RCRA.SURFACE.IM"            "OTHER.SURFACE.I"           
##  [61] "OTHER.DISPOSAL"             "ON.SITE.RELEASE.TOTAL"     
##  [63] "POTW...TRNS.RLSE"           "POTW...TRNS.TRT"           
##  [65] "POTW...TOTAL.TRANSFERS"     "M10"                       
##  [67] "M41"                        "M62"                       
##  [69] "M40.METAL"                  "M61.METAL"                 
##  [71] "M71"                        "M81"                       
##  [73] "M82"                        "M72"                       
##  [75] "M63"                        "M66"                       
##  [77] "M67"                        "M64"                       
##  [79] "M65"                        "M73"                       
##  [81] "M79"                        "M90"                       
##  [83] "M94"                        "M99"                       
##  [85] "OFF.SITE.RELEASE.TOTAL"     "M20"                       
##  [87] "M24"                        "M26"                       
##  [89] "M28"                        "M93"                       
##  [91] "OFF.SITE.RECYCLED.TOTAL"    "M56"                       
##  [93] "M92"                        "OFF.SITE.ENERGY.RECOVERY.T"
##  [95] "M40.NON.METAL"              "M50"                       
##  [97] "M54"                        "M61.NON.METAL"             
##  [99] "M69"                        "M95"                       
## [101] "OFF.SITE.TREATED.TOTAL"     "UNCLASSIFIED"              
## [103] "TOTAL.TRANSFER"             "TOTAL.RELEASES"            
## [105] "RELEASES"                   "ON.SITE.CONTAINED"         
## [107] "ON.SITE.OTHER"              "OFF.SITE.CONTAIN"          
## [109] "OFF.SITE.OTHER.R"           "ENERGY.RECOVER.ON"         
## [111] "ENERGY.RECOVER.OF"          "RECYCLING.ON.SITE"         
## [113] "RECYCLING.OFF.SIT"          "TREATMENT.ON.SITE"         
## [115] "TREATMENT.OFF.SITE"         "PRODUCTION.WSTE..8.1.8.7." 
## [117] "ONE.TIME.RELEASE"           "PROD_RATIO_OR_.ACTIVITY"   
## [119] "PRODUCTION.RATIO"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# make a smaller tri dataset with minimal variable columns}
\NormalTok{tri2017\_sm }\OtherTok{\textless{}{-}}\NormalTok{ tri2017 }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(YEAR, FACILITY.NAME, ZIP, ST, LATITUDE, LONGITUDE, CHEMICAL, ELEMENTAL.METAL.INCLUDED, CLEAN.AIR.ACT.CHEMICAL, CARCINOGEN, PFAS, STACK.AIR, WATER, UNIT.OF.MEASURE, UNDERGROUND, LANDFILLS, LAND.TREATMENT, OFF.SITE.RELEASE.TOTAL, OFF.SITE.RECYCLED.TOTAL, OFF.SITE.ENERGY.RECOVERY.T, FUGITIVE.AIR)}

\CommentTok{\# how many sites in each state?}
\FunctionTok{table}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{ST)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   AK   AL   AR   AS   AZ   CA   CO   CT   DC   DE   FL   GA   GU   HI   IA   ID 
##  267 2192 1494    3  888 3840  809  731   20  193 1808 2348   42  176 1841  402 
##   IL   IN   KS   KY   LA   MA   MD   ME   MI   MN   MO   MP   MS   MT   NC   ND 
## 4022 3508 1287 1940 3021 1013  547  334 3104 1562 1940   37 1117  376 2376  442 
##   NE   NH   NJ   NM   NV   NY   OH   OK   OR   PA   PR   RI   SC   SD   TN   TX 
##  866  293 1137  318  612 1990 5184 1414  871 3817  368  259 1981  317 2258 8766 
##   UT   VA   VI   VT   WA   WI   WV   WY 
##  884 1376   36  109 1123 2885  850  337
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# convert to pounds}
\NormalTok{multiplier }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{UNIT.OF.MEASURE }\SpecialCharTok{==} \StringTok{"Grams"}\NormalTok{, }\DecValTok{1} \SpecialCharTok{/} \FloatTok{453.592}\NormalTok{, }\DecValTok{1}\NormalTok{)}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{FUGITIVE.AIR }\OtherTok{=}\NormalTok{ multiplier }\SpecialCharTok{*}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{FUGITIVE.AIR}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{STACK.AIR }\OtherTok{=}\NormalTok{ multiplier }\SpecialCharTok{*}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{STACK.AIR}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{WATER }\OtherTok{=}\NormalTok{ multiplier }\SpecialCharTok{*}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{WATER}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{UNIT.OF.MEASURE }\OtherTok{=} \StringTok{"Pounds"}

\CommentTok{\# create overall sums}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{FUGITIVE.AIR[}\FunctionTok{is.na}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{FUGITIVE.AIR)] }\OtherTok{=} \DecValTok{0}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{STACK.AIR[}\FunctionTok{is.na}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{STACK.AIR)] }\OtherTok{=} \DecValTok{0}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{WATER[}\FunctionTok{is.na}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{WATER)] }\OtherTok{=} \DecValTok{0}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{TOTAL.POUNDS }\OtherTok{=}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{FUGITIVE.AIR }\SpecialCharTok{+}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{STACK.AIR }\SpecialCharTok{+}\NormalTok{ tri2017\_sm}\SpecialCharTok{$}\NormalTok{WATER}

\NormalTok{tri2017\_sm}\SpecialCharTok{$}\NormalTok{CARCINOGEN.POUNDS }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(tri2017\_sm}\SpecialCharTok{$}\NormalTok{CARCINOGEN }\SpecialCharTok{==} \StringTok{"YES"}\NormalTok{, tri2017\_sm}\SpecialCharTok{$}\NormalTok{TOTAL.POUNDS, }\DecValTok{0}\NormalTok{)}

\DocumentationTok{\#\# just phthalates}
  \CommentTok{\# Filter the data to select observations with "phthalate" in the CHEMICAL column}
\NormalTok{phthalates }\OtherTok{\textless{}{-}}\NormalTok{ tri2017\_sm }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{grepl}\NormalTok{(}\StringTok{"phthalate"}\NormalTok{, }\FunctionTok{tolower}\NormalTok{(CHEMICAL)))}

\CommentTok{\# View the resulting data}
\FunctionTok{head}\NormalTok{(phthalates)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   YEAR                           FACILITY.NAME       ZIP ST LATITUDE  LONGITUDE
## 1 2017 US ARMY MCALESTER ARMY AMMUNITION PLANT     74501 OK 34.84500  -95.89300
## 2 2017                      FISKARS BRANDS INC     64024 MO 39.33488  -94.24922
## 3 2017             U.S. ARMY TOOELE ARMY DEPOT 840745003 UT 40.54166 -112.37500
## 4 2017                    DOREMUS TERMINAL LLC      7105 NJ 40.72865  -74.12194
## 5 2017              UNIVAR SOLUTIONS-DORAVILLE     30340 GA 33.89596  -84.25365
## 6 2017                      POLY VINYL CO INC.     53085 WI 43.74014  -87.80099
##                     CHEMICAL ELEMENTAL.METAL.INCLUDED CLEAN.AIR.ACT.CHEMICAL
## 1          Dibutyl phthalate                       NO                    YES
## 2 Di(2-ethylhexyl) phthalate                       NO                    YES
## 3          Dibutyl phthalate                       NO                    YES
## 4          Dibutyl phthalate                       NO                    YES
## 5          Dibutyl phthalate                       NO                    YES
## 6 Di(2-ethylhexyl) phthalate                       NO                    YES
##   CARCINOGEN PFAS STACK.AIR WATER UNIT.OF.MEASURE UNDERGROUND LANDFILLS
## 1         NO   NO         0     0          Pounds           0         0
## 2        YES   NO      1057     0          Pounds           0         0
## 3         NO   NO         0     0          Pounds           0         0
## 4         NO   NO         0     0          Pounds           0         0
## 5         NO   NO         0     0          Pounds           0         0
## 6        YES   NO         0     0          Pounds           0         0
##   LAND.TREATMENT OFF.SITE.RELEASE.TOTAL OFF.SITE.RECYCLED.TOTAL
## 1              0                   0.00                       0
## 2              0               44026.43                       0
## 3              0                   0.00                       0
## 4              0                   0.00                       0
## 5              0                   0.00                       0
## 6              0                  20.00                   14729
##   OFF.SITE.ENERGY.RECOVERY.T FUGITIVE.AIR TOTAL.POUNDS CARCINOGEN.POUNDS
## 1                          0     7.37e-03    7.370e-03               0.0
## 2                          0     5.28e+02    1.585e+03            1585.0
## 3                          0     0.00e+00    0.000e+00               0.0
## 4                          0     1.00e+00    1.000e+00               0.0
## 5                        258     2.50e+02    2.500e+02               0.0
## 6                          0     1.62e+01    1.620e+01              16.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# add logged carcinogen (in pounds)}
\NormalTok{phthalates }\OtherTok{\textless{}{-}}\NormalTok{ phthalates }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{log\_carcin =} \FunctionTok{log}\NormalTok{(CARCINOGEN.POUNDS))}

\CommentTok{\# download zip shapefile}
\FunctionTok{options}\NormalTok{(}\AttributeTok{tigris\_use\_cache =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{states }\OtherTok{\textless{}{-}}\NormalTok{ tigris}\SpecialCharTok{::}\FunctionTok{states}\NormalTok{(}\AttributeTok{cb =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{year =} \DecValTok{2020}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_simplify}\NormalTok{(}\AttributeTok{dTolerance =} \FloatTok{1e3}\NormalTok{)}

\CommentTok{\# group by states}
\NormalTok{phthalates\_states }\OtherTok{\textless{}{-}}\NormalTok{ phthalates }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(ST) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(}\AttributeTok{nfacilities =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{st\_drop\_geometry}\NormalTok{()}

\CommentTok{\# rename columns to be able to match}
\FunctionTok{colnames}\NormalTok{(phthalates\_states)[}\DecValTok{1}\NormalTok{] }\OtherTok{=}\StringTok{"state"}
\end{Highlighting}
\end{Shaded}

I loaded in TRI data from 2017. Initially I'd planned to look at all
chemicals, and then I zeroed in on just looking at phthalates, based on
the literature, and future work I plan to do. I cleaned up the data
because the naming convention was strange and had a lot of special
characters in the labels. I converted the units to pounds and also
created overall sums for various categories (which I don't end up using
in my analaysis, but it was a worthy exploration; I explored logging the
phthalate as well). Then, I grouped the phthalate facilities by state
and created a summary variable with the total number of toxic facilities
producing phthalates.

\hypertarget{merge-the-psid-with-the-phthalate-tri}{%
\paragraph{Merge the PSID with the Phthalate
TRI}\label{merge-the-psid-with-the-phthalate-tri}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# unite the two data sets}

\FunctionTok{colnames}\NormalTok{(crosswalk)[}\DecValTok{1}\NormalTok{] }\OtherTok{=}\StringTok{"state"}

\NormalTok{phthalates\_states\_names }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{full\_join}\NormalTok{(phthalates\_states, crosswalk, }\AttributeTok{by =} \StringTok{"state"}\NormalTok{)}

\CommentTok{\# creating the merged dataset of phthalate TRI facilities and psid memory data}
\NormalTok{ph\_psid }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{full\_join}\NormalTok{(psid\_collapsed, phthalates\_states\_names, }\AttributeTok{by =} \StringTok{"STATEFP"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

I merged the PSID data with the phthalate TRI data by state/territory.

\hypertarget{american-community-survey-acs}{%
\subsubsection{American Community Survey
(ACS)}\label{american-community-survey-acs}}

The ACS is nationally representative data collected by the U.S. Census
Bureau, and it provides detailed demographic, social, economic, and
housing information to guide public policy and resource allocation at
the local, state, and national levels; they have 1yr and 5 yr estimates
on variety of metrics.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# add in ACS demographic data to the "ph\_psid" data set}

\FunctionTok{library}\NormalTok{(tidycensus)}
\CommentTok{\#census\_api\_key("YOUR KEY GOES HERE", install = TRUE)}

\NormalTok{remotes}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\StringTok{"walkerke/tidycensus"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Skipping install of 'tidycensus' from a github remote, the SHA1 (b801ccdb) has not changed since last install.
##   Use `force = TRUE` to force installation
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(tidycensus)}

\DocumentationTok{\#\# POPULATION}
\NormalTok{pop }\OtherTok{=} \FunctionTok{get\_decennial}\NormalTok{(}\AttributeTok{geography =} \StringTok{"state"}\NormalTok{, }
                  \AttributeTok{variables =} \StringTok{"P1\_001N"}\NormalTok{, }
                  \AttributeTok{year =} \DecValTok{2020}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
\end{verbatim}

\begin{verbatim}
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{verbatim}
## Note: 2020 decennial Census data use differential privacy, a technique that
## introduces errors into data to preserve respondent confidentiality.
## i Small counts should be interpreted with caution.
## i See https://www.census.gov/library/fact-sheets/2021/protecting-the-confidentiality-of-the-2020-census-redistricting-data.html for additional guidance.
## This message is displayed once per session.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(pop)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"population"}
\FunctionTok{head}\NormalTok{(pop, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 4
##   GEOID NAME          variable population
##   <chr> <chr>         <chr>         <dbl>
## 1 42    Pennsylvania  P1_001N    13002700
## 2 06    California    P1_001N    39538223
## 3 54    West Virginia P1_001N     1793716
## 4 49    Utah          P1_001N     3271616
## 5 36    New York      P1_001N    20201249
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# INCOME}
\NormalTok{variables }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"B19013\_001"}\NormalTok{)  }\CommentTok{\# B19013\_001 represents median household income}

\NormalTok{hh\_income }\OtherTok{\textless{}{-}} \FunctionTok{get\_acs}\NormalTok{(}\AttributeTok{geography =} \StringTok{"state"}\NormalTok{, }\AttributeTok{variables =}\NormalTok{ variables, }\AttributeTok{year =} \DecValTok{2017}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2013-2017 5-year ACS
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(hh\_income)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   GEOID NAME       variable   estimate   moe
##   <chr> <chr>      <chr>         <dbl> <dbl>
## 1 01    Alabama    B19013_001    46472   301
## 2 02    Alaska     B19013_001    76114   979
## 3 04    Arizona    B19013_001    53510   259
## 4 05    Arkansas   B19013_001    43813   401
## 5 06    California B19013_001    67169   192
## 6 08    Colorado   B19013_001    65458   317
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# AGE}
\NormalTok{median\_age }\OtherTok{\textless{}{-}} \FunctionTok{get\_acs}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"B01002\_001"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2016-2020 5-year ACS
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# EDUCATION}
\CommentTok{\# educational attainment over time}
\NormalTok{college\_vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"B15002\_015"}\NormalTok{,}
                  \StringTok{"B15002\_016"}\NormalTok{,}
                  \StringTok{"B15002\_017"}\NormalTok{,}
                  \StringTok{"B15002\_018"}\NormalTok{,}
                  \StringTok{"B15002\_032"}\NormalTok{,}
                  \StringTok{"B15002\_033"}\NormalTok{,}
                  \StringTok{"B15002\_034"}\NormalTok{,}
                  \StringTok{"B15002\_035"}\NormalTok{)}

\NormalTok{years }\OtherTok{\textless{}{-}} \DecValTok{2010}\SpecialCharTok{:}\DecValTok{2019}
\FunctionTok{names}\NormalTok{(years) }\OtherTok{\textless{}{-}}\NormalTok{ years}

\NormalTok{college\_by\_year }\OtherTok{\textless{}{-}} \FunctionTok{map\_dfr}\NormalTok{(years, }\SpecialCharTok{\textasciitilde{}}\NormalTok{\{}
  \FunctionTok{get\_acs}\NormalTok{(}
    \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
    \AttributeTok{variables =}\NormalTok{ college\_vars,}
    \AttributeTok{summary\_var =} \StringTok{"B15002\_001"}\NormalTok{,}
    \AttributeTok{survey =} \StringTok{"acs1"}\NormalTok{,}
    \AttributeTok{year =}\NormalTok{ .x}
\NormalTok{  )}
\NormalTok{\}, }\AttributeTok{.id =} \StringTok{"year"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2010 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2011 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2012 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2013 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2014 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2015 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2016 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2017 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2018 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
## Getting data from the 2019 1-year ACS
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{college\_by\_year }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(NAME, variable, year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4,160 x 8
##    year  GEOID NAME    variable   estimate   moe summary_est summary_moe
##    <chr> <chr> <chr>   <chr>         <dbl> <dbl>       <dbl>       <dbl>
##  1 2010  01    Alabama B15002_015   210128  6920     3161521        5158
##  2 2011  01    Alabama B15002_015   208506  7611     3193078        4624
##  3 2012  01    Alabama B15002_015   224285  6163     3209646        4997
##  4 2013  01    Alabama B15002_015   227472  6646     3225447        5448
##  5 2014  01    Alabama B15002_015   222959  6522     3256766        4841
##  6 2015  01    Alabama B15002_015   237072  8143     3282252        5930
##  7 2016  01    Alabama B15002_015   241303  7386     3300713        5481
##  8 2017  01    Alabama B15002_015   242582  6751     3309607        5907
##  9 2018  01    Alabama B15002_015   250321  7709     3337464        5727
## 10 2019  01    Alabama B15002_015   255317  8535     3360058        5792
## # i 4,150 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{percent\_college\_by\_year }\OtherTok{\textless{}{-}}\NormalTok{ college\_by\_year }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(NAME, year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{numerator =} \FunctionTok{sum}\NormalTok{(estimate),}
            \AttributeTok{denominator =} \FunctionTok{first}\NormalTok{(summary\_est)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{pct\_college =} \DecValTok{100} \SpecialCharTok{*}\NormalTok{ (numerator }\SpecialCharTok{/}\NormalTok{ denominator)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{id\_cols =}\NormalTok{ NAME,}
              \AttributeTok{names\_from =}\NormalTok{ year,}
              \AttributeTok{values\_from =}\NormalTok{ pct\_college)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'NAME'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# RACE/ETHNICITY}
\NormalTok{var20 }\OtherTok{\textless{}{-}} \FunctionTok{load\_variables}\NormalTok{(}\AttributeTok{year =} \DecValTok{2020}\NormalTok{, }\AttributeTok{dataset =} \StringTok{"pl"}\NormalTok{)}
\CommentTok{\# American Indian and Alaskan Native P1\_005N}
\CommentTok{\# White P1\_003N}
\CommentTok{\# Black or African American P1\_004N}
\CommentTok{\# Asian P1\_006N}
\CommentTok{\# Native Hawaiian and Other Pacific Islander P1\_007N}
\CommentTok{\# Some Other Race P1\_008N}
\CommentTok{\# Two or More P1\_009N}
\CommentTok{\# Hispanic or Latino P2\_002N}

\NormalTok{aian }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_005N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{white }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_003N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{black }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_004N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{asian }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_006N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nat\_hw\_pac }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_007N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{other }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_008N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{multiple }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P1\_009N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hisp\_lat }\OtherTok{\textless{}{-}} \FunctionTok{get\_decennial}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"P2\_002N"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2020}\NormalTok{,}
  \AttributeTok{sumfile =} \StringTok{"pl"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2020 decennial Census
## Using the PL 94-171 Redistricting Data Summary File
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# this approach doesn\textquotesingle{}t work {-} I was }
\CommentTok{\# RACE/ETHNICITY}
\CommentTok{\# Specify the variables for race}
\CommentTok{\# variables \textless{}{-} c("B01001\_001", "B02001\_002", "B02001\_003", "B02001\_004", "B02001\_005", "B02001\_006", "B02001\_007", "B02001\_008", "B02001\_009")}

\CommentTok{\# Use the get\_acs function to retrieve the data}
\CommentTok{\# race \textless{}{-} get\_acs(geography = "state", variables = variables, year = 2017)}

\CommentTok{\# Create a data frame with labels for each race}
\CommentTok{\# race\_labels \textless{}{-} data.frame(}
 \CommentTok{\# race\_code = c("B02001\_002", "B02001\_003", "B02001\_004", "B02001\_005", "B02001\_006", "B02001\_007", "B02001\_008", "B02001\_009"),}
 \CommentTok{\# race\_label = c("White", "Black or African American", "American Indian and Alaska Native", "Asian", "Native Hawaiian and Other Pacific Islander", "Some other race", "Two or more races", "Hispanic or Latino"))}

\CommentTok{\# Merge the race labels with the acs\_data\_race}
\CommentTok{\# race\_labeled \textless{}{-} race \%\textgreater{}\%}
 \CommentTok{\# left\_join(race\_labels, by = c("variable" = "race\_code"))}

\CommentTok{\# Spread the data into wide format and clean column names}
\CommentTok{\# race\_wide \textless{}{-} race\_labeled \%\textgreater{}\%}
 \CommentTok{\#  spread(key = race\_label, value = estimate) \%\textgreater{}\%}
 \CommentTok{\#  select({-}variable, {-}moe)}

\CommentTok{\# View the resulting wide{-}format data}
\CommentTok{\# head(race\_wide)}
\end{Highlighting}
\end{Shaded}

I gathered the ACS data via an API and the tidycensus package. I
retrieved population, income, median age, percent college completion,
and race/ethnicity for each state/territory.

\hypertarget{combine-the-datasets-psid-phthalate-tri-and-acs-demographics}{%
\paragraph{Combine the datasets: PSID, Phthalate TRI, and ACS
demographics}\label{combine-the-datasets-psid-phthalate-tri-and-acs-demographics}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# combine ph\_psid and ACS demographics}

\DocumentationTok{\#\# population}
\FunctionTok{colnames}\NormalTok{(pop)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\NormalTok{pop }\OtherTok{\textless{}{-}}\NormalTok{ pop }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{GEOID, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(ph\_psid, pop, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\DocumentationTok{\#\# income}
\FunctionTok{colnames}\NormalTok{(hh\_income)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(hh\_income)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"med\_hh\_income"}
\NormalTok{hh\_income }\OtherTok{\textless{}{-}}\NormalTok{ hh\_income }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{GEOID, }\SpecialCharTok{{-}}\NormalTok{variable, }\SpecialCharTok{{-}}\NormalTok{moe)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, hh\_income, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\DocumentationTok{\#\# age}
\FunctionTok{colnames}\NormalTok{(median\_age)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"med\_age"}
\FunctionTok{colnames}\NormalTok{(median\_age)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\NormalTok{median\_age }\OtherTok{\textless{}{-}}\NormalTok{ median\_age }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{moe, }\SpecialCharTok{{-}}\NormalTok{GEOID, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, median\_age, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\DocumentationTok{\#\# education}
\NormalTok{percent\_college\_by\_year }\OtherTok{\textless{}{-}}\NormalTok{ percent\_college\_by\_year }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"2010"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2011"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2012"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2013"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2014"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2015"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2016"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2018"}\NormalTok{, }\SpecialCharTok{{-}}\StringTok{"2019"}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(percent\_college\_by\_year)[}\DecValTok{1}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(percent\_college\_by\_year)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"percent\_college"}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, percent\_college\_by\_year, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\DocumentationTok{\#\# race}
\FunctionTok{colnames}\NormalTok{(multiple)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(multiple)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"multiple"}
\NormalTok{multiple }\OtherTok{\textless{}{-}}\NormalTok{ multiple }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{GEOID, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, multiple, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(aian)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(aian)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"aian"}
\NormalTok{aian }\OtherTok{\textless{}{-}}\NormalTok{ aian }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, aian, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(white)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(white)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"white"}
\NormalTok{white }\OtherTok{\textless{}{-}}\NormalTok{ white }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{full\_join}\NormalTok{(merged, white, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(black)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(black)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"black"}
\NormalTok{black }\OtherTok{\textless{}{-}}\NormalTok{ black }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, black, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(asian)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(asian)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"asian"}
\NormalTok{asian }\OtherTok{\textless{}{-}}\NormalTok{ asian }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, asian, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(nat\_hw\_pac)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(nat\_hw\_pac)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"nat\_hw\_pac"}
\NormalTok{nat\_hw\_pac }\OtherTok{\textless{}{-}}\NormalTok{ nat\_hw\_pac }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, nat\_hw\_pac, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(other)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(other)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"other"}
\NormalTok{other }\OtherTok{\textless{}{-}}\NormalTok{ other }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, other, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\FunctionTok{colnames}\NormalTok{(hisp\_lat)[}\DecValTok{2}\NormalTok{] }\OtherTok{=}\StringTok{"STATE\_NAME"}
\FunctionTok{colnames}\NormalTok{(hisp\_lat)[}\DecValTok{4}\NormalTok{] }\OtherTok{=}\StringTok{"hisp\_lat"}
\NormalTok{hisp\_lat }\OtherTok{\textless{}{-}}\NormalTok{ hisp\_lat }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\StringTok{"GEOID"}\NormalTok{, }\SpecialCharTok{{-}}\NormalTok{variable)}
\NormalTok{merged }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{right\_join}\NormalTok{(merged, hisp\_lat, }\AttributeTok{by =} \StringTok{"STATE\_NAME"}\NormalTok{)}

\CommentTok{\# save the cleaned and merged data file}
\CommentTok{\# write.csv(merged, file = "merged\_psid\_tri\_acs.csv")}
\end{Highlighting}
\end{Shaded}

I combined the PSID, phthalate TRI, and ACS data together, via the U.S.
state/territory name.

\hypertarget{visualization}{%
\subsection{Visualization}\label{visualization}}

In order to visualize the data, I created a map that depicts the number
of phthalate facilities per state (the ligher the color, the more
facilities). I created a simple plot showing the relationship between
total number of phthalate facilities per state and the number of people
with two or more memory impairments per state. I made a histogram
showing the distribution of answers to the dementia question of interest
(two or more memory impairments). Answering ``1'' means two or more
problems endorsed (477 people in the sample). Answering ``5'' means the
respondent has fewer than two problems endorsed (1,786 people in the
sample. Answering ``0'' means the question was not applicable to the
respondent (24,182 people). I made a chloropleth map depicting the
median age in each state, based in ACS data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# visualize the density of toxic release sites that release phthalate chemicals across the U.S.}

\NormalTok{phthalates\_states }\OtherTok{\textless{}{-}}\NormalTok{ phthalates }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(ST) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise}\NormalTok{(}\AttributeTok{nfacilities =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{st\_drop\_geometry}\NormalTok{()}

\NormalTok{phthalates\_states\_shape }\OtherTok{\textless{}{-}}\NormalTok{ states }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{left\_join}\NormalTok{(phthalates\_states, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}STUSPS\textquotesingle{}} \OtherTok{=} \StringTok{\textquotesingle{}ST\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{nfacilities =} \FunctionTok{replace\_na}\NormalTok{(nfacilities, }\DecValTok{0}\NormalTok{))}

\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ phthalates\_states\_shape, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ nfacilities))}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# visualize the density of two plus mem conditions across the U.S.}
\CommentTok{\#merged\_states\_shape \textless{}{-} states \%\textgreater{}\% left\_join(merged, by = c(\textquotesingle{}STATEFP\textquotesingle{} = \textquotesingle{}STATEFP\textquotesingle{})) \%\textgreater{}\% mutate(twoplus = replace\_na(nfacilities, 0))}

\CommentTok{\#ggplot() +}
 \CommentTok{\# geom\_sf(data = st\_geometry(states))}

\CommentTok{\#ggplot() +}
 \CommentTok{\# geom\_sf(data = phthalates\_states\_shape, aes(fill = nfacilities))}



\CommentTok{\# plot just phthalate TRIs and twoplus}
\FunctionTok{plot}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ totaln, }\AttributeTok{data =}\NormalTok{ merged)}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-6-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(merged, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ totaln, }\AttributeTok{y =}\NormalTok{ twoplus)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Total TRI facilities releasing phthalates"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Total individuals with cognitive impairment"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{size =} \DecValTok{16}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-6-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# showing how many people within the data set respond that they have 2+ memory issues listed on the survey}
\NormalTok{two\_plus }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(psid, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ twoplus)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth =} \DecValTok{1}\NormalTok{, }\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{color =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Whether two or more problems were endorsed for the AD8 Screener?"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"two plus"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{two\_plus}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-6-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \CommentTok{\# 1 Two or more problems endorsed (477)}
  \CommentTok{\# 5 Fewer than two problems endorsed (1,786)}
  \CommentTok{\# 0 Inap.(24,182)}
\FunctionTok{table}\NormalTok{(psid}\SpecialCharTok{$}\NormalTok{twoplus)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##     0     1     5 
## 24182   477  1786
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# median age}
\NormalTok{us\_median\_age }\OtherTok{\textless{}{-}} \FunctionTok{get\_acs}\NormalTok{(}
  \AttributeTok{geography =} \StringTok{"state"}\NormalTok{,}
  \AttributeTok{variables =} \StringTok{"B01002\_001"}\NormalTok{,}
  \AttributeTok{year =} \DecValTok{2017}\NormalTok{,}
  \AttributeTok{survey =} \StringTok{"acs1"}\NormalTok{,}
  \AttributeTok{geometry =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{resolution =} \StringTok{"20m"}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{shift\_geometry}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Getting data from the 2017 1-year ACS
\end{verbatim}

\begin{verbatim}
## The 1-year ACS provides data for geographies with populations of 65,000 and greater.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Styled choropleth of US median age with ggplot2}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ us\_median\_age, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ estimate)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_sf}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{scale\_fill\_distiller}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Greens"}\NormalTok{, }
                       \AttributeTok{direction =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"  Median Age by State, 2019"}\NormalTok{,}
       \AttributeTok{caption =} \StringTok{"Data source: 2019 1{-}year ACS, US Census Bureau"}\NormalTok{,}
       \AttributeTok{fill =} \StringTok{"ACS estimate"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme\_void}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-6-5.pdf}

\hypertarget{methods-analysis}{%
\subsection{Methods \& Analysis:}\label{methods-analysis}}

We utilize the Panel Study of Income Dynamics (PSID) in conjunction with
the Environmental Protection Agency (EPA) Toxic Release Inventory (TRI)
and American Community Survey (ACS) to examine the relationship between
chemical toxicants and ADRD prevalence among the U.S. population.

I performed a linear regression, a multiple linear regression, and
explored which variables explained what percentage of the variation we
are seeing in our data in the relationship between phthalate TRI
facilities, and PSID respondents with two or more cognitive impairments,
the benchmark of ADRD.

I checked the assumptions of linear regression: (1) the population
relationship is linear in parameters with an additive disturbance --
YES, it appears that changes in the independent variables are associated
with constant and proportional changes in the dependent variable,
cognitive impairment (2) Our X variable is exogenous -- YES (3) The X
variable has variation -- YES (4) The population disturbance u is
independently and identically distributed as a normal random variable
with mean zero. And, errors cannot vary with X (homoscedasticity)

Initially, I checked the Q-Q plot to examine how well the outcome
variable and the main predictor variables match up with the normal
distribution. They are both askew at the tails, so the data is deviating
from the normal distribution at the extreme high and extreme low values,
but it is close enough that we proceed with our analysis. I plotted the
residuals, and they appear relatively normally distributed.

The multiple linear regression equation is:
\(cognition = total phthalates + percent college + median age + median household income + multiple races + aian + white + hisplat + black + other + asian + nat_hw_pac\)

``aian'' = American Indian and Alaskan Native ``hisplat'' = Hispanic or
Latino ``nat\_hw\_pac'' = Native Hawaiian and Pacific Islander

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# qq plot for outcome variable and main predictor variable}
\FunctionTok{qqnorm}\NormalTok{(merged}\SpecialCharTok{$}\NormalTok{twoplus)}
\FunctionTok{qqline}\NormalTok{(merged}\SpecialCharTok{$}\NormalTok{twoplus)}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(merged}\SpecialCharTok{$}\NormalTok{totaln)}
\FunctionTok{qqline}\NormalTok{(merged}\SpecialCharTok{$}\NormalTok{totaln)}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# perform a simple regression looking at the number [memory condition] in each state and number TRI in each state}
\NormalTok{tri.twoplus.lm }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ totaln, }\AttributeTok{data =}\NormalTok{ merged)}
\FunctionTok{summary}\NormalTok{(tri.twoplus.lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = twoplus ~ totaln, data = merged)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -172.65  -24.09   -6.54   33.59  267.35 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 16.56358   11.93336   1.388    0.171    
## totaln       0.32282    0.01635  19.748   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 60.31 on 49 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.8884, Adjusted R-squared:  0.8861 
## F-statistic:   390 on 1 and 49 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# adding in demographics}
\NormalTok{tri.plustwo.lm }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ totaln }\SpecialCharTok{+}\NormalTok{ percent\_college }\SpecialCharTok{+}\NormalTok{ med\_age }\SpecialCharTok{+}\NormalTok{ med\_hh\_income }\SpecialCharTok{+}\NormalTok{ multiple }\SpecialCharTok{+}\NormalTok{ aian }\SpecialCharTok{+}\NormalTok{ white }\SpecialCharTok{+}\NormalTok{ hisp\_lat }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ other }\SpecialCharTok{+}\NormalTok{ asian }\SpecialCharTok{+}\NormalTok{ nat\_hw\_pac, }\AttributeTok{data =}\NormalTok{ merged)}
\FunctionTok{summary}\NormalTok{(tri.plustwo.lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = twoplus ~ totaln + percent_college + med_age + med_hh_income + 
##     multiple + aian + white + hisp_lat + black + other + asian + 
##     nat_hw_pac, data = merged)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -96.580 -22.567  -5.545  29.745  81.724 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     -1.483e+02  1.423e+02  -1.042  0.30407    
## totaln           2.450e-01  3.094e-02   7.918 1.46e-09 ***
## percent_college -4.104e-01  1.714e+00  -0.239  0.81203    
## med_age          2.446e+00  3.042e+00   0.804  0.42634    
## med_hh_income    1.047e-03  1.256e-03   0.834  0.40961    
## multiple         4.127e-04  9.898e-05   4.170  0.00017 ***
## aian            -1.384e-04  1.238e-04  -1.118  0.27073    
## white            1.345e-06  6.262e-06   0.215  0.83114    
## hisp_lat        -2.663e-04  7.625e-05  -3.492  0.00123 ** 
## black           -2.379e-05  1.430e-05  -1.664  0.10437    
## other            3.534e-04  1.540e-04   2.295  0.02734 *  
## asian           -1.345e-04  9.591e-05  -1.402  0.16891    
## nat_hw_pac      -3.122e-04  4.051e-04  -0.771  0.44574    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 43.86 on 38 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.9542, Adjusted R-squared:  0.9398 
## F-statistic: 66.02 on 12 and 38 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot multiple linear regression}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ totaln }\SpecialCharTok{+}\NormalTok{ percent\_college }\SpecialCharTok{+}\NormalTok{ med\_age }\SpecialCharTok{+}\NormalTok{ med\_hh\_income }\SpecialCharTok{+}\NormalTok{ multiple }\SpecialCharTok{+}\NormalTok{ aian }\SpecialCharTok{+}\NormalTok{ white }\SpecialCharTok{+}\NormalTok{ hisp\_lat }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ other }\SpecialCharTok{+}\NormalTok{ asian }\SpecialCharTok{+}\NormalTok{ nat\_hw\_pac, }\AttributeTok{data =}\NormalTok{ merged)}

\DocumentationTok{\#\#\# this figure is good}
\NormalTok{model }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{augment}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{melt}\NormalTok{(}\AttributeTok{measure.vars =} \FunctionTok{c}\NormalTok{(}\StringTok{"totaln"}\NormalTok{, }\StringTok{"percent\_college"}\NormalTok{, }\StringTok{"med\_age"}\NormalTok{, }\StringTok{"hisp\_lat"}\NormalTok{), }\AttributeTok{variable.name =} \StringTok{"IV"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ value, }\AttributeTok{y =}\NormalTok{ twoplus)) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\FunctionTok{c}\NormalTok{(}\StringTok{"totaln"}\NormalTok{, }\StringTok{"percent\_college"}\NormalTok{, }\StringTok{"med\_age"}\NormalTok{, }\StringTok{"hisp\_lat"}\NormalTok{), }\AttributeTok{scales =} \StringTok{"free\_x"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# (i) totaln regressed on twoplus}
\NormalTok{mod\_ph}\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ totaln, }\AttributeTok{data =}\NormalTok{ merged) }

\CommentTok{\# (ii) totaln and percent\_college regressed on twoplus}
\NormalTok{mod\_col }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(twoplus }\SpecialCharTok{\textasciitilde{}}\NormalTok{ percent\_college, }\AttributeTok{data =}\NormalTok{ merged)}

\CommentTok{\# can create a new summary object, which will contain the r{-}squared values}
\CommentTok{\# mysumm = summary(mod\_size)}
\CommentTok{\# View(mysumm)}

\CommentTok{\# Recovering R2 from the regressions}
\NormalTok{R2\_ph }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mod\_ph)}\SpecialCharTok{$}\NormalTok{r.squared}
\NormalTok{R2\_col }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mod\_col)}\SpecialCharTok{$}\NormalTok{r.squared}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"R2 of density of TRI in a state on cognition is: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(R2\_ph,}\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "R2 of density of TRI in a state on cognition is: 0.89"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 89\% of the variation of size is explained by latitude}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"R2 of percent with college degree on cognition is: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(R2\_col,}\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "R2 of percent with college degree on cognition is: 0"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 0\% of the variation of water temperature is explained by latitude}

\DocumentationTok{\#\# plot residuals}
\NormalTok{residuals }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(model)}

\FunctionTok{plot}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{fitted.values, residuals, }\AttributeTok{main =} \StringTok{"Residuals vs. Fitted Values"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Fitted Values"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)  }\CommentTok{\# Add a horizontal line at y = 0}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(residuals, }\AttributeTok{main =} \StringTok{"Histogram of Residuals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(residuals); }\FunctionTok{qqline}\NormalTok{(residuals, }\AttributeTok{col =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{husted_final_project_files/figure-latex/unnamed-chunk-7-6.pdf}

\hypertarget{interpretation}{%
\subsection{Interpretation}\label{interpretation}}

Applying a simple regression of just ``twoplus'' on ``totaln'' without
all the other control variables first, the correlation coefficient is
0.3228 (SE: 0.0163, P = 0.00).

When we add in the control variables, the magnitude of the coefficient
drops to to 0.2449 (SE: 0.0309, P = 0.00).

This multiple linear regression conveys to us that the number of
facilities producing phthalates in a state is correlated with the number
of individuals in a state that have two or more memory conditions, which
is the benchmark for cognitive impairment and likely development of
Alzheimer's and related Dementia.

An increase in one unit of total phthalate facilities in the state is
predicted to increase the number of individuals that have two or more
memory conditions by one quarter of a person, holding education, age,
race/ethnicity, and income constant. Of course, a quarter of a person is
a silly measure, but over time and among numerous facilities, it's
substantial.

The variables: people identifying as having multiple races/ethnicities,
people identifying as hispanic or latino, and people identifying their
race as other (so, not white, black, american indian and alaska native,
asian, or native hawaiian and pacific islander) were significant
predicting variables as well.

This analysis in its current form likely suffers from omitted variable
bias. It's possible there is another variable (``z'') that is correlated
with one of our explanatory variables (``x''), and that the omitted
variable influences our outcome variable. For my dissertation, I will
dig into this more, and I also plan to analyze the longitudinal PSID
data for years 2017-2022.

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

Plastic pollution is a modifiable risk factor for ADRD. Identifying
communities harmed by these toxic facilities and channeling resources,
funding, and mitigation efforts is critical. Policy change is needed to
reduce and regulate plastics in commercial products so that avoiding
plastics and plastic pollution is achievable for all populations.

In my future work, I plan to utilize the already available coordinates
of TRI facilities and the restricted access block level data for the
PSID. This will allow for a more precise analysis of the relationship
between TRI facilities and cognition. I plan to hone in the units of
measurement for each of the control variables. Using multiple waves of
PSID data (2017-2022) will allow for analysis over time. Possible
considerations is the number of people with cognitive impairments as TRI
facilities rise over time, holding age constant. Another avenue to
explore would be comparing age and income matched areas in terms of
cognition and differing TRI facility densities, to capture whether TRI
facility pollution is a leading cause of cognition rising in an
underserved census block. A lot to consider, but with time and
longitudinal, precise data, knowledge regarding the role of phthalate
chemicals impacting cognition, and consequently ADRD, should arise.

\hypertarget{references}{%
\subsection{References}\label{references}}

Covert, B. (2016, February 18). Race Best Predicts Whether You Live Near
Pollution. Www.thenation.com.
\url{https://www.thenation.com/article/archive/race-best-predicts-whether-you-live-near-pollution/}
**featured in CleanEarth4Kids

Environmental Protection Agency. (2017). Toxics Release Inventory (TRI)
Data for the year 2017. Retrieved from
\url{https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-data-files-calendar-years-1987-2017}

Factor-Litvak, P., Insel, B., Calafat, A. M., Liu, X., Perera, F., Rauh,
V. A., \& Whyatt, R. M. (2014). Persistent Associations between Maternal
Prenatal Exposure to Phthalates on Child IQ at Age 7 Years. PLOS ONE,
9(12), e114003. \url{https://doi.org/10.1371/journal.pone.0114003}

Frey, Christopher H., 2022, EPA Researchers Release Cumulative Impacts
Report, Prioritizing Environmental Justice in New Research Cycle.
Environmental Protection Agency. Science Matters.

Lei, M., Menon, R., Manteiga, S., Alden, N., Hunt, C., Alaniz, R. C.,
Lee, K., \& Jayaraman, A. (2019). Environmental Chemical Diethylhexyl
Phthalate Alters Intestinal Microbiota Community Structure and
Metabolite Profile in Mice. mSystems, 4(6), 10.1128/msystems.00724-19.
\url{https://doi.org/10.1128/msystems.00724-19}

Li, N., Papandonatos, G. D., Calafat, A. M., Yolton, K., Lanphear, B.
P., Chen, A., \& Braun, J. M. (2020). Gestational and childhood exposure
to phthalates and child behavior. Environment International, 144,
106036. \url{https://doi.org/10.1016/j.envint.2020.106036}

Marmot, M. (2017). The Health Gap: The Challenge of an Unequal World:
the argument. International Journal of Epidemiology, 46(4), 1312--1318.
\url{https://doi.org/10.1093/ije/dyx163}

Panel Study of Income Dynamics, public use dataset {[}restricted use
data, if appropriate{]}. Produced and distributed by the Survey Research
Center, Institute for Social Research, University of Michigan, Ann
Arbor, MI (2017).

Parker, L. (2022, May 2). Microplastics are in our bodies. how much do
they harm us? Environment. Retrieved September 29, 2022, from
\url{https://www.nationalgeographic.com/environment/article/microplastics-are-in-our-bodies-how-much-do-they-harm-us?loggedin=true}

PSID AD8 Dementia Screen, link:
\url{chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://psidonline.isr.umich.edu/Publications/Papers/tsp/2019-01_AD8_Dementia_PSID.pdf}

Tierney, A.L., Nelson, C.A., 2009. Brain development and the role of
experience in the early years. Zero Three 30, 9--13.

U.S. Census Bureau. (2010-2020) American Community Survey Public Use
Microdata Samples. Retrieved via tidycensus package.

Walker K, Herman M (2023). tidycensus: Load US Census Boundary and
Attribute Data as `tidyverse' and `sf'-Ready Data Frames. R package
version 1.5, \url{https://walker-data.com/tidycensus/}.

\end{document}
